back/config/routes.rb
Rails.application.routes.draw do
  namespace :v1 do
    resources :categories
    resources :items do
      collection do
        get '/:code/find_by_code', to: 'items#find_by_code'
      end
    end
    resources :products
    resources :users do
      collection do
        post :login
      end
    end
  end
end

back/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

back/app/models/category.rb
class Category < ApplicationRecord
  belongs_to :product
  has_many :items

  def no_items?
    items.empty?
  end
end

back/app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category

  validates :code, uniqueness: true

  def product
    category&.product
  end
end

back/app/models/product.rb
class Product < ApplicationRecord
  TYPES = HashWithIndifferentAccess.new({ inventory: 1, not_inventory: 2 })

  belongs_to :user

  has_many :categories
  has_many :items, through: :categories
end

back/app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable

  ROLES = HashWithIndifferentAccess.new({ admin: 1, store: 2 })

  has_many :products

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    role == ROLES[:admin]
  end
end

back/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  def authenticate
    @current_user = User.find_by_email(params[:email])
    if @current_user&.valid_password?(params[:password])
      render json: @current_user, status: :ok
    else
      error_message = "Email or password incorrect."
      render json: { error: error_message }, status: :unauthorized
    end
  end

  def validate_authentication_token
    authenticate_or_request_with_http_token do |token, _options|
      @current_user = User.find_by_authentication_token(token)
      head(:unauthorized) unless @current_user.present?
      @current_user
    end
  end
end

back/app/controllers/v1/categories_controller.rb
module V1
  class CategoriesController < ApplicationController
    before_action :validate_authentication_token
    before_action :set_category, only: %i[show update]

    def index
      if @current_user.role == User::ROLES[:admin]
        render json: Category.all, status: :ok
      else
        product_ids = @current_user.products.pluck(:id)
        render json: Category.where(product_id: product_ids), status: :ok
      end
    end

    def show
      if user_allowed?
        render json: @category, status: :ok
      else
        render json: { 'error': 'Cannot get this category' }, status: :unprocessable_entity
      end
    end

    def create
      product = Product.find category_params[:product_id]
      if product.user_id == @current_user.id
        category = Category.new(category_params)
        if category.save
          render json: { "message": "Category has been created_successfully.", "product_id": category.id }, status: :created
        else
          render json: { errors: category.errors.full_messages }, status: :unprocessable_entity
        end
      else
        render json: { "error": "You are not authorized to modify this product" }, status: :unprocessable_entity unless product.user_id == @current_user.id
      end
    rescue ActiveRecord::RecordNotFound
      render json: { "error": "Product does not exist" }, status: :unprocessable_entity
    end

    def update
      if user_allowed?
        render json: @category, status: :ok if @category.update(category_params)
      else
        render json: { 'error': 'Cannot update this category' }, status: :unprocessable_entity
      end
    end

    private

    def category_params
      params.require(:category).permit(:name, :product_id, :picture, :stock, :price)
    end

    def set_category
      @category = Category.find params[:id]
    end

    def user_allowed?
      @category && (@current_user.role == User::ROLES[:admin] || @category.product.user_id == @current_user.id)
    end
  end
end

back/app/controllers/v1/items_controller.rb
module V1
  class ItemsController < ApplicationController
    before_action :validate_authentication_token

    def create
      if Category.find(item_params[:category_id]).no_items?
        item = Item.new(item_params)
        if item.save
          render json: { message: "Item has been saved successfully" }, status: 201
        else
          render json: { errors: item.errors.full_messages }, status: 422
        end
      else
        render json: { error: 'Cannot add more items to this category' }, status: 422
      end
    end

    def update
      item = Item.find_by(id: params[:id])
      if item.present?
        render json: item.as_json, status: :ok if item.update(item_params)
        render json: { error: 'Could not update the item' }, status: :unprocessable_entity unless item.update(item_params)
      else
        render json: { error: "There is no any item with this id: #{params[:id]}" }, status: :unprocessable_entity
      end
    end

    def find_by_code
      item = Item.find_by_code(params[:code])
      item = nil if item.present? && item.product&.user&.id != @current_user.id && !@current_user.admin?
      render json: item.as_json if item.present?
      render json: { error: 'There is no any item with this code' }, status: 404 unless item.present?
    end

    private

    def item_params
      params.require(:item).permit(:code, :status, :category_id)
    end
  end
end

back/app/controllers/v1/products_controller.rb
module V1
  class ProductsController < ApplicationController
    before_action :validate_authentication_token

    def index
      products = Product.all
      products = Product.where(user_id: @current_user.id) if @current_user.role == User::ROLES[:store]

      render json: products
    end

    def show
      product = Product.find params[:id]
      render json: product, status: :ok
    rescue ActiveRecord::RecordNotFound
      render json: { error: 'There is no any product with this id' }, status: :not_found
    end

    def update
      product = Product.find_by(id: params[:id])

      if product.update(product_params)
        render json: product, status: :ok
      else
        render json: { error: product.errors }, status: :not_found
      end
    end

    def create
      product = Product.new(product_params)
      product.user_id = @current_user.id
      if product.save
        render json: { "message": "Product has been created successfully.", "product_id": product.id }, status: :created
      else
        render json: { errors: product.errors.full_messages }, status: :unprocessable_entity
      end
    end

    private

    def product_params
      params.require(:product).permit(:name, :description, :inventory)
    end
  end
end

back/app/controllers/v1/users_controller.rb
module V1
  class UsersController < ApplicationController
      before_action :authenticate, only: :login
      before_action :validate_authentication_token, except: %i[login create]

      def create
        user = User.new(user_params)
        if user.save
          render json: user.as_json(only: %i[email authentication_token]), status: :created
        else
          render json: { errors: user.errors.full_messages }, status: 422
        end
      end

      def show; end

      def update; end

      def destroy; end

      def login; end

      private    

      def user_params
        params.require(:user).permit(:name, :email, :username, :password, :authentication_token, :picture, :role)
      end
  end
end

back/app/helpers/application_helper.rb
module ApplicationHelper
end

back/app/helpers/categories_helper.rb
module CategoriesHelper
end

back/app/helpers/items_helper.rb
module ItemsHelper
end

back/app/helpers/products_helper.rb
module ProductsHelper
end

back/app/helpers/users_helper.rb
module UsersHelper
end

back/app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

back/app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

back/app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Picture</th>
      <th>Stock</th>
      <th>Price</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.picture %></td>
        <td><%= category.stock %></td>
        <td><%= category.price %></td>
        <td><%= category.product_id %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

back/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

back/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @category.picture %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @category.stock %>
</p>

<p>
  <strong>Price:</strong>
  <%= @category.price %>
</p>

<p>
  <strong>Product:</strong>
  <%= @category.product_id %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

back/app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

back/app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

back/app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.code %></td>
        <td><%= item.status %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

back/app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

back/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @item.code %>
</p>

<p>
  <strong>Status:</strong>
  <%= @item.status %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

back/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Back</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

back/app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

back/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

back/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Type</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.type %></td>
        <td><%= product.user_id %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

back/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

back/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @product.type %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

back/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :auth_token %>
    <%= form.text_field :auth_token %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

back/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

back/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Username</th>
      <th>Password</th>
      <th>Auth token</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.auth_token %></td>
        <td><%= user.picture %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

back/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

back/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Auth token:</strong>
  <%= @user.auth_token %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @user.picture %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>